name: Build
on: [push]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-rc1
      - name: Go Env
        run: go env
      - name: Test
        run: go test -v .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-rc1
      - name: Go Env
        run: go env
      - name: Build
        run: go build -v .