name: Build
on: [push]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'tip', '1.16.0-rc1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: '!contains(${{ matrix.go-version }}, "beta") && !contains(${{ matrix.go-version }}, "rc")'
          go-version: ${{ matrix.go-version }}
      - name: Go Env
        run: go env
      - name: Test
        run: go test -v .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        go-version: [ 'tip', '1.16.0-rc1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: '!contains(${{ matrix.go-version }}, "beta") && !contains(${{ matrix.go-version }}, "rc")'
          go-version: ${{ matrix.go-version }}
      - name: Go Env
        run: go env
      - name: Build
        run: go build -v .